= Connection guide

[cols="1,2"]
|===
|From |To

|From a macOS app:
|   To other apps on the same machine: xref:IAC.adoc[] +
    To apps on Windows/macOS/iOS over Wi-Fi/LAN: xref:RTP-MIDI.adoc[] +
    To apps on macOS/iOS/Android over Bluetooth: xref:BLE-MIDI.adoc[] +
    To apps on iOS over USB: xref:IDAM.adoc[] +
    To apps on Android over USB: xref:USB-MIDI.adoc[] +
    To MIDI devices over USB: xref:USB-MIDI.adoc[]

|From a Windows app
|   To other apps on the same machine: xref:IAC.adoc[] +
    To apps on Windows/macOS/iOS over Wi-Fi/LAN: xref:RTP-MIDI.adoc[] +
    To apps on Android over USB: xref:USB-MIDI.adoc[] +
    To MIDI devices over USB: xref:USB-MIDI.adoc[]

|From an iOS app
|   To other apps on the same device: xref:IAC.adoc[] +
    To apps on macOS/iOS/Android over Bluetooth: xref:BLE-MIDI.adoc[] +
    To apps on Windows/macOS/iOS over Wi-Fi/LAN: xref:RTP-MIDI.adoc[] +
    To apps on macOS over USB: xref:IDAM.adoc[] +
    To apps on Android over USB: xref:USB-MIDI.adoc[] +
    To MIDI devices over USB: xref:USB-MIDI.adoc[]

|From an Android app
|   To apps on macOS/iOS over Bluetooth: xref:BLE-MIDI.adoc[] +
    To apps on Windows/macOS/Android over USB: xref:USB-MIDI.adoc[] +
    To MIDI devices over USB: xref:USB-MIDI.adoc[]

|From a MIDI device
|   To apps on macOS/iOS/Android over Bluetooth: xref:BLE-MIDI.adoc[] +
    To apps on Windows/macOS/iOS/Android over USB: xref:USB-MIDI.adoc[]
|===