= Play notes with your keyboard
:experimental:

When WebMIDICon is focused, you can use these keys to play MIDI notes with your QWERTY keyboard. There are 2 keymaps available.

== Piano Keymap

The piano keymap is based on the piano keyboard layout.

image::keyboard.svg[]

=== Access higher notes

If you hold down the kbd:[Alt] key, the notes on the upper row will be shifted up an octave, giving you access to a higher range.

== Isomorphic Keymap

The isomorphic keymap is based on the B-system chromatic button accordian layout.

image::keyboard-chromatic.svg[]

The idea is that for any given key…

* The key on the top right is whole tone up.
* The key on the bottom right is semitone up.

Using this system, you can combine semitones and whole tones to create any musical interval.
It lets you play in any key without changing the fingering, and it uses the keyboard more efficiently, allowing you to reach more notes.

image::isomorphic.svg[]

== Transpose

The keys marked as green are used for setting the transpose option. This lets you quickly change keys.

[#sustain]
== Sustain pedal

You can hold down the kbd:[Space] key to activate xref:pedal.adoc[the sustain pedal].
